version: '3'

services:
  localhost:
    image: bitnami/postgresql
    container_name: feedback-widget
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=feedback-widget-api
